listing, spaces, cleanup, tests.

diff --git a/choowm b/choowm
--- a/choowm
+++ b/choowm
@@ -105,6 +105,7 @@ unity
 uwm
 windowlab
 windowmaker
+wingo
 wm2
 wmfs
 wmfs2
@@ -119,11 +120,12 @@ abort () { fail "Aborted." ; }
 nowim () { fail "No window manager found!" ; }
 usage () { errx "Usage: $0 [ -n | -i initialwm ]" ; }
 
-unset butn btns dryrun hasinit initial names paths temp wim
+unset butn btns dryrun hasinit initial listing names paths temp wim
 
 # parse options
 while [[ $# -gt 0 ]]; do
     case $1 in
+        -l) listing=1 ;;
         -n) dryrun=1 ;;
         -i) [[ -n $2 ]] || usage ; initial=$2 ; shift ;;
         *) usage ;;
@@ -135,24 +137,22 @@ done
 declare -a names
 declare -a paths
 
-# locate every known window manager
+# locate every window manager
 for w in "${WIMS[@]}"; do
-    # absolute path?
-    if [[ $w =~ / ]]; then
+    # remove arguments
+    n=${w/ *}
+    # has directories?
+    if [[ $n =~ / ]]; then
+        # get path
+        p=$n
         # get basename
-        n=${w##*/}
-        # remove arguments
-        n=${n/ *}
-        # absolute path
-        p=${w%/*}/$n
+        n=${n##*/}
         # executable file
         [[ -x $p && -f $p ]] || continue
     else
-        # remove arguments
-        n=${w/ *}
-        # locate path
+        # locate executable
         p=$(command -v $n) || continue
-        # include arguments
+        # include path
         w=${p%/*}/$w
     fi
     # s is n without pre/postfix
@@ -162,7 +162,7 @@ for w in "${WIMS[@]}"; do
     if [[ -v initial && ! -v hasinit ]]; then
         if [[ $p = $initial || $n = $initial || $s = $initial ]]; then
             # remember wm index
-            : ${hasinit:=${#names[@]}}
+            hasinit=${#names[@]}
         fi
     fi
     # remember wm name and location
@@ -183,6 +183,12 @@ trap 'rm -f -- "$temp"' 0
 if [[ -n $hasinit ]]; then
     # the button has been given
     butn=$hasinit
+elif [[ -n $listing ]]; then
+    # print wms
+    for ((i=0; $i < ${#names[@]}; i++)) ; do
+        printf '%-2d  %-11s  %s\n' $i "${names[$i]}" "${paths[$i]}"
+    done
+    exit 0
 elif [[ -n $zenity ]]; then
     # construct a zenity dialog
     cat >>$temp <<-'EOF'
@@ -221,6 +227,10 @@ x=$?
 [[ $x = 1 || ! $butn =~ ^[0-9]+$ ]] && abort
 [[ $butn -ge ${#names[@]} ]] && abort
 wim=${paths[$butn]}
+
+# cleanup
+rm -f -- "$temp"
+trap '' 0
 
 # -n option only echoes
 [[ $dryrun = 1 ]] && exec echo "$wim"
